project:
  type: default
  render:
    - "**/*.qmd"
    - "**/*.Rmd"
    - "!themes/"
    - "!renv/"
    - "!node_modules/"

editor_options:
  markdown:
    wrap: sentence

format:
  hugo-md:
    filters:
      - figure-to-markdown.lua
  pdf:
    pdf-engine: xelatex
    mainfont: "DejaVu Sans"
    monofont: "DejaVu Sans Mono"
