
[build] 
  publish = "public"
  command = "hugo "

[context.production.environment]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


