---
title: "AboutMe"
---

I am a cognitive neuroscientist based in Oslo, Norway, and works at the [Center for Lifespan Changes in Brain and Cognition](www.oslobrains.no). I'm passionate about cognitive neuroscience, using R and teaching the world the wonders of R. Doing all I can to improve gender diversity in the R-community though [RLadies-Oslo](https://twitter.com/RLadies_Oslo)
   
### Education  
2012 - 2016 &nbsp;&nbsp;&nbsp; PhD in Cognitive Neuroscience, University of Oslo  
2009 - 2011 &nbsp;&nbsp;&nbsp; MPhil in Cognitive Neuroscience, University of Oslo  
2005 - 2009 &nbsp;&nbsp;&nbsp; BA in Cognitive Psychology, University of Oslo  

### Publications  

```{r echo=F, warning=F, error=F}
library(tidyverse); library(scholar)
get_citation_history("7NkxgWQAAAAJ") %>% 
    mutate(cumulative=cumsum(cites)) %>% 
    gather(Metric, val, -1) %>% 
    ggplot(aes(x=year, y=val, group=Metric, color=Metric)) + 
    geom_line() + 
    theme_minimal() + 
  labs(y="Googe citations", x="Year")
```
Walhovd, Fjell, Westerhausen, Nyberg, Ebmeier et al. (2018) Healthy minds from 0–100 years: Optimising the use of European brain imaging cohorts (“Lifebrain”). _European Psychiatry_ 47, 76-87

**Mowinckel**, Alnæs, Pedersen, Ziegler,Fredriksen et al. (2017) Increased default-mode variability is related to reduced task-performance and is evident in adults with ADHD. _NeuroImage: Clinical_ 16, 369-382

Ziegler, Pedersen, **Mowinckel** & Biele (2016) Modelling ADHD: a review of ADHD theories through their predictions for computational models of decision-making and reinforcement learning. _Neuroscience & Biobehavioral Reviews_ 71, 633-656

**Mowinckel**, Pedersen, Eilertsen & Biele (2015) A meta-analysis of decision-making and attention in adults with ADHD. _Journal of Attention Disorders_ 19 (5), 355-367

**Mowinckel**, Espeseth & Westlye (2012) Network-specific effects of age and in-scanner subject motion: a resting-state fMRI study of 238 healthy adults. _Neuroimage_ 63 (3), 1364-1373	80
