---
title: GAMM spaghetti plots in R with ggplot
author: Dr. Mowinckel
date: '2018-03-07'
slug: gamm-spaghetti-plots-in-r-with-ggplot
categories:
  - R
tags: []
draft: true
---

Here we go! Stepping into the world of blogging through R and blogdown! This is both super exciting and slightly scary, I have not really shared code online like I plan here before. But I guess we start somewhere. And we start with plotting.

A co-worker was working on some generalized additive mixed models (GAMM) through the R package mgvc. The analyses work very well, and results were as expected. There were also some built in plotting functions for the gamm output in R. However, they were with base-r, and we all know base-r is not the most beautiful plotting application. Also, we have a need to a spaghetti plot in the background, as the whole point with a GAMM is that we have repeated data, and showing those in the background is very essential. **This** is not easily done in base-r.

So I went googling, and in my frustration, there was very little help in what I found. The standard 