baseURL      = "https://drmowinckels.io/"  # Your domain name. Must end with "/"
buildDrafts  = false               # Include pages with draft status of true
buildFuture  = false               # Include pages with publishdate in the future
